$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: diabetes-deployment
endpoint_name: diabetes-endpoint
model: azureml:diabetes-classification-model:1
instance_type: Standard_DS3_v2
instance_count: 1
