name: Train ML Model with Linting, Unit Test, Dev and Prod Environments

on:
  push:
    branches:
      - main

env:
  workspace-name: mlflow-ci-cd
  resource-group: mlflow_lab

permissions:
  id-token: write
  contents: read

jobs:
  linting:
    name: Run Linting (Flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Flake8
        run: |
          python -m pip install flake8

      - name: Run lint checks
        run: |
          flake8 src/model/

  unit-test:
    name: Run Unit Tests (pytest)
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest tests/test_train.py

  experiment:
    name: Train in Development
    environment: development
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Azure ML CLI extension
        run: az extension add -n ml -y

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Submit Azure ML Job (Development Dataset)
        run: |
          az ml job create --file ./src/job.yml \
          --inputs data_path=azureml://datastores/workspaceblobstore/paths/diabetes-dev-folder \
          --workspace-name ${{ env.workspace-name }} \
          --resource-group ${{ env.resource-group }}

  production:
    name: Train in Production
    environment: production
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Azure ML CLI extension
        run: az extension add -n ml -y

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Submit Azure ML Job (Production Dataset)
        run: |
          az ml job create --file ./src/job.yml \
          --inputs data_path=azureml://datastores/workspaceblobstore/paths/diabetes-prod-folder \
          --workspace-name ${{ env.workspace-name }} \
          --resource-group ${{ env.resource-group }}
