name: Full ML CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  workspace-name: mlflow-ci-cd
  resource-group: mlflow_lab

permissions:
  id-token: write
  contents: read

jobs:
  linting:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 src/model/

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install pytest and requirements
        run: |
          pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest tests/test_train.py

  experiment:
    name: Train Model (Development)
    environment: development
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure ML CLI
        run: az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Submit Azure ML Job (Development Dataset)
        run: |
          az ml job create --file ./src/job.yml \
          --workspace-name ${{ env.workspace-name }} \
          --resource-group ${{ env.resource-group }}

  production:
    name: Train Model (Production)
    environment: production
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure ML CLI
        run: az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Submit Azure ML Job (Production Dataset Override)
        run: |
          az ml job create --file ./src/job.yml \
          --set inputs.training_data.path=azureml:diabetes-prod-folder:1 \
          --workspace-name ${{ env.workspace-name }} \
          --resource-group ${{ env.resource-group }}

  deploy:
    name: Deploy Registered Model
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure ML CLI
        run: az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Online Endpoint
        run: |
          az ml online-endpoint create \
              --workspace-name ${{ env.workspace-name }} \
              --resource-group ${{ env.resource-group }} \
              --file src/deploy/endpoint.yml
      - name: Deploy Model to Endpoint
        run: |
          az ml online-deployment create --name blue \
          --endpoint-name diabetes-endpoint-cicd \
          --model diabetes-classification-model:1 \
          --instance-type Standard_DS2_v2 \
          --instance-count 1 \
          --workspace-name ${{ env.workspace-name }} \
          --resource-group ${{ env.resource-group }}
